server.port=8080
spring.application.name=catalog

# Configuración de Neon DB (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-dry-union-a8qce74w-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_46QRlWSZGpNE
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ejecutar el schema.sql al arrancar para inicializar las tablas
spring.sql.init.mode=always
# Usar el schema.sql de la carpeta frontend que hicimos antes
spring.sql.init.schema-locations=file:frontend/db/schema.sql
